name: Build

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    # https://github.com/actions/runner/issues/241#issuecomment-577360161
    shell: 'script -q -e -c "bash {0}"'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: unionai/flytectl-setup-action@v0.0.1
        with:
          version: '0.1.10'
      - name: "Setup env"
        run: mkdir ~/.flyte
      - name: setup sandbox
        run: flytectl sandbox start
      - name: fast register
        run: REGISTRY=ghcr.io/flyteorg VERSION=latest make fast_register