name: Serialize Examples

on:
  pull_request:

jobs:
  serialize-example:
    name: Serialize
    strategy:
      matrix:
        directory: [ "core", "integrations", "case_studies" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-${{ matrix.directory }}/
          key: release-snacks-${{ matrix.directory }}
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          mkdir -p cookbook/release-snacks /tmp/release-snacks-${{ matrix.directory }}/
          make -C cookbook/${{ matrix.directory }} serialize
          make -C cookbook archive
  goreleaser:
    name: Release Case studies example
    runs-on: ubuntu-latest
    needs: [ serialize-example ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case_studies/
          key: release-snacks-case_studies
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-integrations
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          ref: ${{ steps.bump-version.outputs.tag }}
      - name: Copy artifacts
        run: |
          mkdir -p cookbook/release-snacks
          cp -r /tmp/release-snacks-core/* cookbook/release-snacks/
          cp -r /tmp/release-snacks-case_studies/* cookbook/release-snacks/
          cp -r /tmp/release-snacks-integrations/* cookbook/release-snacks/
      - uses: unionai/flytectl-setup-action@v0.0.1
      - name: setup sandbox
        run: flytectl sandbox start --flytesnacks=$GITHUB_WORKSPACE
      - name: Register workflow
        run: make -C cookbook register-workflow-ci
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}