name: Master

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    name: Bump Version
    if: github.event.commits[0].author.name != 'goreleaserbot'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch
  core-releaser:
    name: Release Core example
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make serialize type=core
          mkdir -p release-snacks /tmp/release-snacks-core/
          make release type=core 
          cp -r release-snacks/* /tmp/release-snacks-core/
  integrations-releaser:
    name: Release Integrations example
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-plugins
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make serialize type=integrations
          mkdir -p /tmp/release-snacks-integrations/
          make release type=integrations
          cp -r release-snacks/* /tmp/release-snacks-integrations/
  case_studies-releaser:
    name: Release Case studies example
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case-studies/
          key: release-snacks-case-studies
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make serialize type=case_studies
          mkdir -p /tmp/release-snacks-case-studies/
          make release type=case_studies
          cp -r release-snacks/* /tmp/release-snacks-case-studies/
  goreleaser:
    name: Release Case studies example
    runs-on: ubuntu-latest
    needs: [core-releaser, case_studies-releaser, integrations-releaser]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case-studies/
          key: release-snacks-case-studies
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-plugins
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          ref: ${{ steps.bump-version.outputs.tag }}
      - name: Copy artifacts
        run: |
          mkdir -p release-snacks
          cp -r /tmp/release-snacks-core/* release-snacks/
          cp -r /tmp/release-snacks-case-studies/* release-snacks/
          cp -r /tmp/release-snacks-integrations/* release-snacks/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}