name: Serialize snacks 

on:
  pull_request:

jobs:
  core-releaser:
    name: Release Core example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make serialize type=core
  integrations-releaser:
    name: Release Integrations example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-plugins
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make serialize type=integrations
  case_studies-releaser:
    name: Release Case studies example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case-studies/
          key: release-snacks-case-studies
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make serialize type=case_studies
