name: Serialize snacks 

on:
  pull_request:

jobs:
  core-build:
    name: Build Core example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core-${{ runner.os }}-${{ hashFiles('**/flyte_tests_manifest.json') }}-${{ github.sha }}
      - name: Generate Serialize proto
        env:
          REGISTRY : "ghcr.io/flyteorg"
        run: |
          make -C cookbook/core serialize
          mkdir -p cookbook/release-snacks /tmp/release-snacks-core/
          make -C cookbook archive
          cp -r cookbook/release-snacks/* /tmp/release-snacks-core/
  integrations-build:
    name: Build Integrations example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-plugins-${{ runner.os }}-${{ hashFiles('**/flyte_tests_manifest.json') }}-${{ github.sha }}
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make -C cookbook/integrations serialize
          mkdir -p cookbook/release-snacks /tmp/release-snacks-integrations/
          make -C cookbook archive
          cp -r cookbook/release-snacks/* /tmp/release-snacks-integrations/
  case_studies-build:
    name: Build Case studies example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case-studies/
          key: release-snacks-case-studies-${{ runner.os }}-${{ hashFiles('**/flyte_tests_manifest.json') }}-${{ github.sha }}
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make -C cookbook/case_studies serialize
          mkdir -p cookbook/release-snacks /tmp/release-snacks-case-studies/
          make -C cookbook archive
          cp -r cookbook/release-snacks/* /tmp/release-snacks-case-studies/
  sandbox:
    name: Register & Serialize Test Workflows
    runs-on: ubuntu-latest
    needs: [core-build, case_studies-build, integrations-build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core-${{ runner.os }}-${{ hashFiles('**/flyte_tests_manifest.json') }}-${{ github.sha }}
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case-studies/
          key: release-snacks-case-studies-${{ runner.os }}-${{ hashFiles('**/flyte_tests_manifest.json') }}-${{ github.sha }}
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-plugins-${{ runner.os }}-${{ hashFiles('**/flyte_tests_manifest.json') }}-${{ github.sha }}
      - uses: unionai/flytectl-setup-action@v0.0.1
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          ref: ${{ steps.bump-version.outputs.tag }}
      - name: Copy artifacts
        run: |
          mkdir -p cookbook/release-snacks
          cp -r /tmp/release-snacks-core/* cookbook/release-snacks/
          cp -r /tmp/release-snacks-case-studies/* cookbook/release-snacks/
          cp -r /tmp/release-snacks-integrations/* cookbook/release-snacks/
      - name: setup sandbox
        run: flytectl sandbox start
      - name: Register all examples
        run: make -C cookbook register_workflow_serialized_test

