name: Test snacks 

on:
  pull_request:

jobs:
  core-build:
    name: Build Core example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core
      - uses: unionai/flytectl-setup-action@v0.0.1
        with:
          version: '0.1.10'
      - name: setup sandbox
        run: flytectl sandbox start
      - name: Generate Serialize proto
        run: |
          make -C cookbook/core serialize
      - name: Register core example workflow
        run : make -C cookbook/core register
      - name: run pytest #TODO
        run: echo "Hello" 
  integrations-build:
    name: Build Integrations example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: unionai/flytectl-setup-action@v0.0.1
        with:
          version: '0.1.10'
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-plugins
      - name: Generate Serialize proto
        run: |
          make -C cookbook/integrations serialize
      - name: Register integrations example workflow
        run : make -C cookbook/integrations register
      - name: run pytest #TODO
        run: echo "Hello" 
  case_studies-build:
    name: Build Case studies example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: unionai/flytectl-setup-action@v0.0.1
        with:
          version: '0.1.10'
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case-studies/
          key: release-snacks-case-studies
      - name: Generate Serialize proto
        run: |
          make -C cookbook/case_studies serialize
      - name: Register case_studies example workflow
        run : make -C cookbook/case_studies register
      - name: run pytest #TODO
        run: echo "Hello" 