name: Sandbox Register

on:
  pull_request:
    paths-ignore:
      - 'cookbook/docs/**'
      - 'cookbook/deployment/**'

defaults:
  run:
    # https://github.com/actions/runner/issues/241#issuecomment-577360161
    shell: 'script -q -e -c "bash {0}"'

jobs:
  list:
    runs-on: ubuntu-latest
    name: "Create a list of packages"
    steps:
      - uses: actions/checkout@v2
      - name: "Provide the list"
        id: create-list
        run: echo "::set-output name=packages::$(find cookbook -mindepth 1 -maxdepth 5 -type f -name Dockerfile -exec dirname '{}' \; | sort | jq  --raw-input . | jq --slurp . | jq -c .)"
    outputs:
      packages: "${{ steps.create-list.outputs.packages }}"

  build:
    name: Sandbox Register
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: "${{ fromJson(needs.list.outputs.packages) }}"
        command: [ "register", "fast_register" ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: unionai/flytectl-setup-action@v0.0.1
      - name: setup sandbox
        run: make setup
      - name: Serialize Examples
        env:
          SANDBOX: "1"
        run: |
          make -C cookbook/${{ matrix.directory }} serialize
          make -C cookbook/${{ matrix.directory }} ${{ matrix.command }}
