name: Sandbox Register

on:
  pull_request:
    paths-ignore:
      - 'cookbook/docs/**'
      - 'cookbook/deployment/**'

defaults:
  run:
    # https://github.com/actions/runner/issues/241#issuecomment-577360161
    shell: 'script -q -e -c "bash {0}"'

jobs:
  list:
    runs-on: ubuntu-latest
    name: "Create a list of packages"
    steps:
      - uses: actions/checkout@v2
      - name: "Provide the list"
        id: create-list
        run: echo "::set-output name=packages::$(find cookbook -mindepth 1 -maxdepth 2 -type f -name Dockerfile -exec dirname '{}' \; | sort | jq --raw-input . | jq --slurp . | jq -c .)"
    outputs:
      packages: "${{ steps.create-list.outputs.packages }}"

  serialize:
    name: Sandbox
    runs-on: ubuntu-latest
    needs: [ "list" ]
    strategy:
      matrix:
        directory: "${{ fromJson(needs.list.outputs.packages) }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Serialize Examples
        env:
          SANDBOX: "1"
        run: |
          make -C ${{ matrix.directory }} serialize
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "$(sed -i '' 's_/_-_' ${{ matrix.directory }})"
          path: ${{ matrix.directory }}/_pb_output/*
  register:
    name: Sandbox
    runs-on: ubuntu-latest
    needs: [ "list", "serialize" ]
    #    strategy:
    #      matrix:
    #        directory: "${{ fromJson(needs.list.outputs.packages) }}"
    #        command: [ "register", "fast_register" ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: unionai/flytectl-setup-action@v0.0.1
      - name: setup sandbox
        run: make setup
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Serialize Examples
        env:
          SANDBOX: "1"
        run: |
          ls **
#          make -C ${{ matrix.directory }} ${{ matrix.command }}
