name: Sandbox Register

on:
  pull_request:
    paths-ignore:
      - 'cookbook/docs/**'
      - 'cookbook/deployment/**'

defaults:
  run:
    # https://github.com/actions/runner/issues/241#issuecomment-577360161
    shell: 'script -q -e -c "bash {0}"'

jobs:
  build:
    name: Sandbox Register
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ "core", "integrations", "case_studies" ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: unionai/flytectl-setup-action@v0.0.1
      - name: setup sandbox
        run: make setup
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Serialize Examples
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          SANDBOX=1 make -C cookbook/${{ matrix.directory }} register
      - name: Serialize Examples
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          SANDBOX=1 make -C cookbook/${{ matrix.directory }} fast_register
